version: '3.8'

services:
  # BEGIN minio
  minio:
    image: quay.io/minio/minio
    restart: always
    command: server --console-address ":9090" /data
    environment:
      TZ: Europe/Paris
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ${s3_data_dir:-./s3_data}:/data
    env_file:
      - ./.env
    networks:
      - ecodev-network
  # END minio
  # BEGIN ecodev_cloud
  ecodev_cloud:
    command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root --port 80 --NotebookApp.token='${jupyter_token}'
    volumes:
      - ${test_dir:-./tests}:/app/tests
      - ./ecodev_cloud:/app/ecodev_cloud
      - ${data_dir:-./data}:/app/data
    ports:
      - ${jupyter_port:-5000}:80
  # END ecodev_cloud
  #BEGIN Azurite
  azurite_cloud:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite_cloud
    env_file:
      - ./.env
    hostname: azurite_cloud
    restart: always
    command: azurite-blob --blobHost 0.0.0.0 -l data
    volumes:
       - ${azurite_data_dir:-./azurite_data}:/opt/azurite/data
    networks:
      - ecodev-network
    ports:
      - "10001:10000"
  #END Azurite
